name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          
      - name: Build CrowdCards
        run: |
          npm run build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: crowdcards
          entrypoint: "apps/web/build/index.js"

      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.11.x
          npm run lhci
        #env:
        #  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        continue-on-error: true
